/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as multicallSol from "./Multicall.sol";
export * as test from "./test";
export { NftMarketplace__factory } from "./NftMarketplace__factory";
