/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multicallSol from "./Multicall.sol";
export type { multicallSol };
import type * as test from "./test";
export type { test };
export type { NftMarketplace } from "./NftMarketplace";
export * as factories from "./factories";
export type { Multicall3 } from "./Multicall.sol/Multicall3";
export { Multicall3__factory } from "./factories/Multicall.sol/Multicall3__factory";
export { NftMarketplace__factory } from "./factories/NftMarketplace__factory";
export type { BasicNft } from "./test/BasicNft";
export { BasicNft__factory } from "./factories/test/BasicNft__factory";
